config/routes.rb
Rails.application.routes.draw do

  # root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#create'
  get  '/login',  to: 'users#new'
  post  '/validate',  to: 'users#validate'
  post  '/users/save',  to: 'users#save'
  resources :users



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # attr_accessor :name, :email, :password, :typeu
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
    else
      # Create an error message.
      flash[:danger] = 'Invalid email/password combination' # Not quite right!

      render 'new'
    end
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def index
  end

  def show
  end

  def root
  end

  def validate
    @user = User.where(user_params_email_password).first

    if @user
      render 'root'
    else
      flash[:success] = "User No Found!"
      render 'new'
    end
  end

  def save
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :typeu)
  end

  def user_params_email_password
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppTask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, url: users_save_path) do |f| %>

        <%= f.label :Name %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
        <br>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
        <br>
        <%= f.label :type_user %>
        <%= f.select :typeu, options_for_select([['Operator', 1], ['Patient', 2]]) %>
        <br>
        <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Log In</h1>
<div class="row">

  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, url: validate_path) do |f| %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
  </div>
</div>

app/views/users/root.html.erb
<% provide(:title, 'DashBoard') %>
<% provide(:button_text, 'DashBoard') %>
<h1>DashBoard</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">


  </div>
</div>